[package]
name = "iam-macros"
version = "0.1.0"
edition = "2024"
license-file.workspace = true

[lib]
path = "./lib.rs"
proc-macro = true

[dependencies]
proc-macro2 = "1.0.103"
quote = "1.0.42"
syn = { version = "2.0.110", features = ["parsing"] }
